# 系统参数配置文件

SAVE_DIR: "D:/myproject/pyProject/LangChainProject/Paper-Agent/data"
# 知识库配置
KB_TYPE: "chroma"
enable_reranker: False
tmpdb_top_k: 2
tmpdb_similarity_threshold: 0.05
top_k: 5
similarity_threshold: 0.05

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/app.log
  max_bytes: 10485760
  backup_count: 5

# 缓存配置
cache:
  enabled: true
  type: memory
  ttl: 3600
  max_size: 1000

# 请求配置
request:
  timeout: 30
  max_retries: 3
  retry_delay: 1

# 并发配置
concurrency:
  max_workers: 4
  max_connections: 10

# 文件路径配置
paths:
  data_dir: data
  cache_dir: cache
  output_dir: output
  temp_dir: temp

# 性能配置
performance:
  batch_size: 10
  chunk_size: 1000
  enable_streaming: true

# 安全配置
security:
  enable_rate_limit: true
  rate_limit_per_minute: 60
  enable_cors: true
  allowed_origins: "*"
